### ISSUE TITLE
Can it be used in jupyter notebook?

### ISSUE THREAD

**Issue by markqiu** [markmap/markmap#106]
Thanks!

**Comment by vorel99** [comment]
Hello, 
there is a way.

add following cell to your jupyter notebook:
```python
from IPython.display import IFrame
IFrame(src='PATH_TO_EXPORTED_HTML', width=1100, height=700)
```
Set `width` and `height` properly, for your needs. 


There is possibility, that the mindmap wont be visible at .ipynb file, but after export to html, it works.

example export command:
```bash
jupyter nbconvert --to html PATH_TO_IPYNB_FILE
```

**Comment by markqiu** [comment]
Thank you very much! @vorel99
