### ISSUE TITLE
Levels of Expansion in toolbar 

### ISSUE THREAD

**Issue by 7Eltantawy** [markmap/markmap#122]
Can u provide the ability to control levels of expansion to the toolbar in the bottom

**Comment by gera2ld** [comment]
Can you elaborate what it's for? we already have `initialExpandLevel` and recursive toggling, does that meet your demands?

**Comment by HasanEltantawy** [comment]
@gera2ld  Thanks for replying
I know about `initialExpandLevel ` but I'm using html view which is provided by U and I'll need to control the levels of expansion visually from the bottom bar

**Comment by tamer73** [comment]
same here ... initialExpandLevel not working with  <script src="https://cdn.jsdelivr.net/npm/markmap-autoloader@0.16"></script>

**Comment by gera2ld** [comment]
Just checked, `initialExpandLevel` works as expected. @tamer73 Please open a new issue with detailed reproduction if the issue persists.
