### ISSUE TITLE
the exported html rendered failed when there are lots of images in the markdown

### ISSUE THREAD

**Issue by h2lin** [markmap/markmap#131]
with 2 images, the image render succeed：
![A2](https://user-images.githubusercontent.com/16922217/192797199-38d69a1c-69cb-44a3-9dc3-44e5942354d5.png)

with lots of images, the image maybe render failed:
![A1](https://user-images.githubusercontent.com/16922217/192797407-b85589ca-04bc-41c2-9b76-0327615ea1db.png)

The VSCode plug has the same problem. When there are lots of images in the markdown, if export as html, then the html will fail to render the images. It seems that the height is too low:
![A3](https://user-images.githubusercontent.com/16922217/192799843-cf80c529-5f81-4878-af89-412c29ef8d1b.png)

**Comment by JianqiangDing** [comment]
Hi, thanks for this nice tool, may I ask you how to modify the size of embedded images? it seems that the plugin always show the image too small, even vanished. 

I triked this issue by adding some texts before embedding some image, and the image alway adaptive its width to the text width.

any suggestions would be helpful. thank you!

**Comment by gera2ld** [comment]
This issue should have been fixed.
