### ISSUE TITLE
[improvement] Computing power consumption

### ISSUE THREAD

**Issue by kbarkati** [markmap/markmap#132]
First, thank you for markmap!

I noticed my laptop gets hotter when using markmap, especially when typing with the rendering open, so I'm raising this question: what could be done to make it less computing-intensive?

**Comment by gera2ld** [comment]
Maybe you can disable the animations by

```yaml
markmap:
  duration: 0
```

Or increase the debounce time to reduce unnecessary rendering. But that is an external change and not related to this project.

**Comment by kbarkati** [comment]
Thank you, it seems to be better: while I haven't make true benchmarks, I feel my laptop is cooler.

So I decided to set it in the global options:

```json
{
  "colorFreezeLevel": 2,
  "duration": 0
}
```

Maybe `duration` could be renamed or aliased as `animationDuration` to make it clearer.

**Comment by gera2ld** [comment]
> I feel my laptop is cooler.

If your are talking about the website, it might be due to a cache issue and should have been fixed.
