### ISSUE TITLE
Is there any way I can set the proper size?

### ISSUE THREAD

**Issue by dzylikecode** [markmap/markmap#134]
The first mindmap is nice, but the second one is too small because of its unsuitable height.

![image](https://user-images.githubusercontent.com/71511961/193979042-4efa334d-7899-4e68-b829-63d234fff548.png)

So is there any way to set the proper size according to the content of markdown?

**Comment by dzylikecode** [comment]
![image](https://user-images.githubusercontent.com/71511961/193985292-d801c7c2-ca32-4e14-9655-1269e6136142.png)

There is already an idea in my mind.

1. calculate the width and depth of the mindmap
2. calculate the ratio $ratio = \frac {height} {width}$
3. set the style of HTML elements, maybe like this: `<svg id="mind-1" width="100%" height=ratio*height></svg>`

The problem is that I don't know how to set the height attribute. I have googled it and got an answer which suggested using the CSS to control the style like below:

```CSS
#mind-1 {
  width: 100%
  height: 75vh
}
```

But I want to set the height dynamically according to the data of markdown.

So what should I do?

**Comment by gera2ld** [comment]
`mm` is an instance of `Markmap`. After `mm.setData`, you can get the ratio like this:

```js
const { minX, maxX, minY, maxY } = mm.state;
const naturalWidth = maxY - minY;
const naturalHeight = maxX - minX;
const ratio = naturalHeight / naturalWidth;
```

**Comment by dzylikecode** [comment]
@gera2ld Thanks. it's very useful. Can you tell me what to do next if I already set the width to 100%?
This is the Html element.
```Html
<svg id="mind-1" width="100%"></svg>
```
Then how to set the height in JS? I'm new to Javascript, I only know the syntax but have less knowledge about JS applied in the browser.

```JS
const elem = document.getElementById("mind-1");
// then how to set height
```

**Comment by dzylikecode** [comment]
```js
markmapSvg.push(function () {
                  let elem = document.getElementById(
                    "markmap-svg-" + currentNum
                  );
                  const mm = new markmap.Markmap(elem, null);
                  if (data) {
                    mm.setData(data);
                    const { minX, maxX, minY, maxY } = mm.state;
                    const naturalWidth = maxY - minY;
                    const naturalHeight = maxX - minX;
                    const ratio = naturalHeight / naturalWidth;
                    elem.style.width = naturalWidth + "px";
                    elem.style.height = naturalHeight + "px";
                    mm.fit(); // always fit for the first render
                  }
                });
```

maybe I don't need to set the width to 100%. If you have any better ideas, please tell me. Thank you very much @gera2ld , you really help me a lot.
