### ISSUE TITLE
[feature-request] Show markdown tables

### ISSUE THREAD

**Issue by danilofaria** [markmap/markmap#137]
I see that markdown tables are not supported, but inserting tables in mindmaps is a very common thing.
I am not sure how hard it would be to get that implemented, but it certainly would be a great feature.

**Comment by Wangha01993** [comment]
+1

**Comment by ZacheryAU** [comment]
I finally found an alternative way to insert table is using KaTeX array.  [](https://talk.dynalist.io/t/simple-tables-using-katex-arrays/5169)

**Comment by gera2ld** [comment]
It's supported in v0.16+
