### ISSUE TITLE
How do I Disabled Prism Syntax highlight?

### ISSUE THREAD

**Issue by Kevin1596** [markmap/markmap#140]
I current building a blog with code and using Prism Syntax highlight for content, then when import markmap to my react app, it import addition prism syntax highlight cause the Styles is overrided. 
Could you help me with this?

**Comment by gera2ld** [comment]
You can remove the prism plugin completely:

```ts
import { Transformer, builtInPlugins } from 'markmap-lib';

const plugins = builtInPlugins.filter(plugin => plugin.name !== 'prism');
const transformer = new Transformer(plugins);
```

Or keep the plugin for transformation but skip loading the assets:

```ts
const { root, features } = transformer.transform(markdown);
features.prism = false; // turn it off explicitly
const { styles, scripts } = transformer.getUsedAssets(features);
```
