### ISSUE TITLE
Styles added with the style option are not in the page after render.

### ISSUE THREAD

**Issue by james-tindal** [markmap/markmap#153]
They are used to calculate things during render but are no longer on the page afterward.

**Comment by gera2ld** [comment]
Please provide the steps to reproduce it.

**Comment by james-tindal** [comment]
Actually, this only happens when updating with the setData method. 

https://codesandbox.io/s/loving-chaplygin-u5unvn?file=/src/index.js

**Comment by gera2ld** [comment]
It was fixed in 781aff10f0d584011bf02958562f6e32ad3842a2 .
Will release later.
