### ISSUE TITLE
VS COde integration - newbie question - meta data is not reflected in the generated html

### ISSUE THREAD

**Issue by lakshmias** [markmap/markmap#154]
Thanks for the tool.
I am trying to use this in VSCode for a sample md file
I specified the metadata for the md file like 

`---
`Java:
`  colorFreezeLevel: 2
`  initialExpandLevel: 1
`---
`# Java
`## Jakarta EE

I was expecting the colorFreeze & initialExpand not to be shown as a node and only to be considered for drawing the mindmap. However the metadata too is shown in the mindmap.

Can someone help me to resolve this?

![image](https://user-images.githubusercontent.com/13296750/217166067-654dfe30-9858-4497-ad2b-7e3dd40e8da2.png)

**Comment by gera2ld** [comment]
There should be an empty row after the second `---`, and all options should be under `markmap`.

````md
---
markmap:
  colorFreeLevel: 2
  initialExpandLevel: 1
---
                  <!-- empty line -->
content here
````
