### ISSUE TITLE
[BUG] KaTeX not rendered correctly

### ISSUE THREAD

**Issue by GrimPixel** [markmap/markmap#155]
- [ x ] I have searched for existing issues that already reported this problem and found none
- [  x ] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**
On https://markmap.js.org/repl, click on “More Katex examples”, press “Ctrl +A”, two unnecessary X appeared.

**Comment by gera2ld** [comment]
This is expected, the same happens in https://katex.org/ too.
![image](https://user-images.githubusercontent.com/3139113/218463896-17d024d2-8675-4999-bc86-1010d853a9ff.png)
