### ISSUE TITLE
[BUG] 友友们，碰到报错：node_modules/d3-array/src/cumsum.js: Only '=' operator can be used for specifying default value，该怎么处理啊

### ISSUE THREAD

**Issue by startgirl** [markmap/markmap#168]
- [x] I have searched for existing issues that already reported this problem and found none
- [x] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Environment:**

- OS: [e.g. macOS]
- Browser: [e.g. chrome, safari]
- Browser Version: [e.g. 22]

**Additional context**

**Comment by startgirl** [comment]
![企业微信截图_16838749763802](https://github.com/markmap/markmap/assets/45334778/f6aa7cf9-82e6-4672-b0cc-28afceca8e8c)

**Comment by gera2ld** [comment]
> Note that issues without a reproduction may be closed immediately!
