### ISSUE TITLE
addthis.com on the website (https://markmap.js.org/)

### ISSUE THREAD

**Issue by ghhv** [markmap/markmap#169]
Hi,

Can I suggest removing this.. not sure why it needs to be consuming 30-40% CPU in Chrome on Windows.

And I've got 24 cores.. is it mining crypto or something?

![image](https://github.com/markmap/markmap/assets/13160762/f36ba543-7ab9-4bc2-a7d1-18c95f81c884)

**Comment by gera2ld** [comment]
Removed

**Comment by ghhv** [comment]
yeah, it was a bit odd. Very old code too.. I think it was dated 2019/20..Correction.. still got it open "AddThis - v8.28.7 - 20201026;"
