### ISSUE TITLE
how to use markmap-toolbar in reactjs

### ISSUE THREAD

**Issue by Aries-Rabbit** [markmap/markmap#173]
i wanna use toolbar to make customize toolbar with percent, but i dont know how to use

**Comment by gera2ld** [comment]
Here is an example without React:

https://github.com/markmap/markmap-vscode/blob/09e5d92649e3a77699a4042f3378c0283f4d1408/assets/app.js#L48-L65

However you can wrap the render part in a React component effect.

**Comment by Aries-Rabbit** [comment]
sure, i wanna use it in reactjs, are u have any example

**Comment by gera2ld** [comment]
You can check this demo: https://stackblitz.com/edit/markmap?file=markmap-hooks.tsx
