### ISSUE TITLE
Thank you note

### ISSUE THREAD

**Issue by Zeioth** [markmap/markmap#174]
I recently moved to neovim and it's been super easy to use markmap without the need of having vim-coc thanks to markman-cli. Thank you so much for making this software 😄

```lua
-- My lua keybinding to run markmap for the active buffer
os.execute("markmap " .. vim.api.nvim_get_current_buf(bufnr)) -- Before running this command you must install "yarn global add markmap-cli".
```

**Comment by gera2ld** [comment]
👍

**Comment by Zeioth** [comment]
I've ported coc-markmap to neovim in lua, in case you wanna add it to the [web docs](https://markmap.js.org/docs/markmap):
https://github.com/Zeioth/markmap.nvim
