### ISSUE TITLE
can not set JSON options if it parsed form json in reactjs

### ISSUE THREAD

**Issue by Aries-Rabbit** [markmap/markmap#175]
i have my json content, which called form api:
const jsonContent = `{
  "markmap": {
    "colorFreezeLevel": 2,
    "maxWidth": 300,
    "color": "#2980b9",
    "initialExpandLevel": 1
  },
  "content": "# Travel in Da Lat, Vietnam\\n\\n## Attractions\\n- Xuan Huong Lake\\n- Valley of Love\\n- Da Lat Flower Gardens\\n- Truc Lam Zen Monastery\\n- Datanla Waterfall\\n- Langbiang Mountain\\n- Crazy House\\n- Bao Dai Summer Palace\\n\\n## Outdoor Activities\\n- Trekking in Bidoup Nui Ba National Park\\n- Cycling around Da Lat city\\n- Canyoning in Datanla Falls\\n- Kayaking on Tuyen Lam Lake\\n- Horseback riding at Da Lat Equestrian Club\\n\\n## Cultural Experiences\\n- Visit local coffee plantations\\n- Explore Da Lat Market
}
`;

and parse it for the format like type input:

 useEffect(() => {
    const data = JSON.parse(jsonContent);
    const { markmap, content } = data;
    const markmapOptions = Object.entries(markmap)
      .map(([key, value]) => `{"  "}${key}: ${value}`)
      .join("\n");
    const originalFormat = `---
markmap:
${markmapOptions}

---

${content}
`;

i console.log originalFormat, it work if i copy and paste in input of https://markmap.js.org/repl
it also render markmap for me but not apply markmapOptions for my markmap, what should i do

**Comment by gera2ld** [comment]
Please format your code or provide a minimal reproduction. It's totally unreadable.

**Comment by gera2ld** [comment]
Frontmatter must be followed by an empty line:

````md
---
# frontmatter here
markmap:
  ...
---
                    <!-- an empty line is required -->
# other content
````
