### ISSUE TITLE
how to make Download as interactive HTML in reactjs

### ISSUE THREAD

**Issue by Aries-Rabbit** [markmap/markmap#178]
your project just awesome, i try to use different way to download my mindmap as an html file, but it not interactive also dont have toolbar at the bottom right, how to make it, thanks u

**Comment by gera2ld** [comment]
`fillTemplate` from `markmap-lib` generates an interactive HTML.

The toolbar needs to be added by yourself.

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/markmap-toolbar@0.14.4/dist/style.css">
<script src="https://cdn.jsdelivr.net/npm/markmap-toolbar@0.14.4"></script>
```

```ts
// markmap-toolbar@0.14
const el = Toolbar.create(mm);
el.style.position = 'absolute';
el.style.bottom = '0.5rem';
el.style.right = '0.5rem';

// `container` could be the element that contains both the markmap and the toolbar
container.append(el);
```

**Comment by nanqic** [comment]
May I see the code of https://markmap.js.org/repl Download as interactive HTML? 
I wanna add this feature to my own toolbar, with react.

**Comment by gera2ld** [comment]
Check https://markmap.js.org/docs/packages--markmap-lib

**Comment by gera2ld** [comment]
Should be `transformer.fillTemplate(root, assets, { jsonOptions: { ... } })`.
