### ISSUE TITLE
NO PUEDO DESCARGAR EN FORMATO HTLM

### ISSUE THREAD

**Issue by raulmendez88** [markmap/markmap#189]
ESTOY TENIENDO PROBLEMAS AL NO PODER  DESCARGAR EN NINGUN NAVEGADOR LOS ESQUEMAS EN FORMATO HTLM, ¿ALGÚN USUARIO POR AQUI LE PASA LO MISMO? 

AGRADECERÍA UNA RESPUESTA

**Comment by gera2ld** [comment]
It was a bug and fixed now.
