### ISSUE TITLE
[BUG] Markmap from cdn error

### ISSUE THREAD

**Issue by magnussentio** [markmap/markmap#190]
Looks like there is a new issue with markmap when loading the library from the cdn. Some kind of function error with t.buildJSItem and "Transformer is not a constructor".

Not sure what the issue is but you can see the error with this code using the codepen link:
[Codepen of Markmap example](https://codepen.io/stwind/pen/JjZXabb)
Using chrome to experiment with markmap.

**Comment by gera2ld** [comment]
Fixed in `markmap-lib@0.15.1`
