### ISSUE TITLE
[Feature Request] Can link support local file:///D:/test ?

### ISSUE THREAD

**Issue by lizhihome** [markmap/markmap#196]
If the link supports local file link, this tool can also be used for organizing concepts/mind storm, it will be great.
Thanks,

**Comment by gera2ld** [comment]
I think it's not possible due to security reasons.

**Comment by lizhihome** [comment]
it's not possible to start windows explorer, but it can display the linked folder in browser, for example:
		<a href="D:\abc\Markdown" >My Test</a> 
it works in html.
