### ISSUE TITLE
I don't use latex, can I remove it?

### ISSUE THREAD

**Issue by nanqic** [markmap/markmap#226]
Thanks for this project!
The  bundle size of latex is biggest, but I won't use it, how can I exclude this lib?

![20240103165506](https://github.com/markmap/markmap/assets/34978586/deca401d-bcde-42fa-b045-56e99a64a0d4)

**Comment by gera2ld** [comment]
Sorry I can't help with so little information.
It is more like a bundling issue rather than an issue with this library.
Feel free to open a discussion thread and provide more information there.

**Comment by gera2ld** [comment]
Maybe an easy way is to simply externalize `katex` and load it from `window.katex`. It doesn't matter if you don't use it anyway.
I'll provide a build without any plugins in the future.

**Comment by nanqic** [comment]
Hello, thank you for your reply. 
I'm trying to externalize markmap-lib with [importToCDN](https://github.com/MMF-FE/vite-plugin-cdn-import),

``` javascript
importToCDN({
        modules: [
          autoComplete('react'),
          autoComplete('react-dom'),
          {
            name: "markmap-lib",
            var: 'MarkmapLib',
            path: 'https://unpkg.com/browse/markmap-lib@0.15.8/dist/index.js',
            version: "0.15.8"
          },
        ],
      })
```
but I got `ReferenceError: MarkmapLib is not defined` error.

Looking forward to the arrival of the version without any plugins!
