### ISSUE TITLE
[Support] Could you please help to verify the Katex display in Vue?

### ISSUE THREAD

**Issue by gymaerl** [markmap/markmap#227]
Hi there,

Seems the katex content is not workable when I tried it in Vue3.
Any other settings are required?

Here is my snapshot, thanks.
<img width="1381" alt="image" src="https://github.com/markmap/markmap/assets/55907098/76165a3a-0592-4455-9afe-11a4b74448b5">

Best regards,

**Comment by gymaerl** [comment]
This is my own's snapshot.
<img width="1381" alt="image" src="https://github.com/markmap/markmap/assets/55907098/83d6d9ae-89f7-4c1c-987c-664766ef29d4">

**Comment by gera2ld** [comment]
Hi @gymaerl you need to load the required assets.
Here is how to load all available assets:

```ts
export const transformer = new Transformer();
const { scripts, styles } = transformer.getAssets();
loadCSS(styles);
loadJS(scripts);
```

The demo is also updated.
