### ISSUE TITLE
Windows 10 or 11 run command "markmap -w some_markdown_file.md" occured an Error: Could not find root dir

### ISSUE THREAD

**Issue by whong1618** [markmap/markmap#228]
In Windows 10 or 11, I install markmap-cli using command below:

yarn global add markmap-cli

when I try to run command "markmap -w some_markdown_file.md" occured an error below:
------------------------------------------------------
C:\Users\xxxx>markmap -w some_markdown_file.md
file:///C:/Users/xxxx/yarn/global/node_modules/markmap-cli/dist/index.js:60
    throw new Error("Could not find root dir");
          ^

Error: Could not find root dir
    at file:///C:/Users/xxxx/yarn/global/node_modules/markmap-cli/dist/index.js:60:11
    at async fetchAssets (file:///C:/Users/xxxx/yarn/global/node_modules/markmap-cli/dist/index.js:389:21)
    at async Command.<anonymous> (file:///C:/Users/xxxx/yarn/global/node_modules/markmap-cli/dist/index.js:512:7)

Node.js v20.10.0
------------------------------------------------------

The error is related to lines 55-62 of the file 'index.js':
------------------------------------------------------
const rootDirPromise = packageDirectory({
  cwd: new URL(import.meta.url).pathname
});
const assetsDirPromise = rootDirPromise.then((rootDir) => {
  if (!rootDir)
    throw new Error("Could not find root dir");
  return resolve(rootDir, `.${ASSETS_PREFIX}`);
});
------------------------------------------------------

I try to read the file 'index.js'， and use a simple but not good enough
method to solve it. It is using the two line below instead of the original
lines 55-62 in file 'index.js'.
----------------------------------------------------------------
const rootDirPromise = "C:/Users/xxxx/yarn/global/node_modules/markmap-cli";
const assetsDirPromise = resolve(rootDirPromise, `.${ASSETS_PREFIX}`);
------------------------------------------------------

Now the command "markmap -w some_markdown_file.md" can work.

I believe that the author of markmap-cli can fix this problem in a better way.
I am looking forward to it very much! 

Markmap is a very useful and
user-friendly tool, thank you for sharing!

**Comment by gera2ld** [comment]
Can you try `yarn global add markmap-cli@0.15.9-alpha.16`? Thanks.

**Comment by MarcoBuess** [comment]
@gera2ld Had the same issue. Just for you to confirm, this fixes it.

**Comment by gera2ld** [comment]
@MarcoBuess did you try `markmap-cli@0.15.9-alpha.17`?
