### ISSUE TITLE
[Help] SVG structure (colour rendering) not working for indented nested lists 

### ISSUE THREAD

**Issue by EsperantoP** [markmap/markmap#230]
SVG structure (the parameter `colourFreezeLevel`) seems not working for nested lists:
![image](https://github.com/markmap/markmap/assets/81968849/adeba224-c367-4063-953a-815ac6569f37)
(Please ignore the content💀)

Context:
Why is this issue here?
> (I am not a developer hence I am unable to solve this problem myself :(
> I saw the level of heading was limited in HTML as well as in Markdown... I personally think it is quite unfortunate but reasonable.
> As you see in the picture, my "notes" perhaps required many "heading levels" to complete but it is not available.
> Hence I saw the solution for this in the markmap [Documentation - FAQ](https://markmap.js.org/docs/faq)
> So I think it is somehow reasonable as why I use neasted lists (?)

I've reviewed some issues with this kind of issue.
Accroding to the [Solution](https://markmap.js.org/docs/json-options):
```
---
markmap:
    "color" = "blue"
---
```
> even this "blue " is not in brackets [], it will still work as I have used it, though unfortunately not for me...

or

```
---
markmap:
    "color" = "#000000"
----
````
are possible solution to this problem.
But it does change the colour overall, so the parameter `colorFreezeLevel` does not function anymore (though it was not functioning with neasted lists before)

I would appreciate it if there are some possible solutions!
Thanks!

**Comment by EsperantoP** [comment]
I heavily apologies that I forgot to mention my markmap is the plugin verion in VS Code.

Thanks :)

**Comment by gera2ld** [comment]
Could you provide a full example of your Markdown file? The snippet above seems invalid.

BTW here is a working example:

```md
---
markmap:
  colorFreezeLevel: 2
---

## Topics

- topic 1
  - child 1
    - child 1.1
    - child 1.2
  - child 2
    - child 2.1
    - child 2.2
- topic 2
  - child 2.1
  - child 2.2
```

**Comment by EsperantoP** [comment]
> Could you provide a full example of your Markdown file? The snippet above seems invalid.
> 
> BTW here is a working example:
> 
> ```
> ---
> markmap:
>   colorFreezeLevel: 2
> ---
> 
> ## Topics
> 
> - topic 1
>   - child 1
>     - child 1.1
>     - child 1.2
>   - child 2
>     - child 2.1
>     - child 2.2
> - topic 2
>   - child 2.1
>   - child 2.2
> ```

I really appreciate it1 <3
Here is my markdown:
[SB1.md](https://github.com/markmap/markmap/files/14269847/SB1.md)

I guess this is caused by missing a heading initially?

**Comment by EsperantoP** [comment]
> I really appreciate it1 <3 Here is my markdown: [SB1.md](https://github.com/markmap/markmap/files/14269847/SB1.md)
> 
> I guess this is caused by missing a heading initially?

I heavily apologise, I used British format to spell the parameter `colorFreezeLevel` hence I spelled it as `colourFreezeLevel` that obviously wouldn't work as the variable assgined is not used in the statement💀

**Comment by EsperantoP** [comment]
**Conclution:**
This problem caused by *mispelling* of variable `colorFreezeLevel`.

All the function of the program is fine and working well.

It problem is caused by an external, artificial factor *which is me*.

All nested lists should work in any kind of format if with a suitable indentation.

**Acknowledgement:**
Appreciating the dev to contribute thic problem just after the issue posted 5 hours later!
