### ISSUE TITLE
How to use Toolbar with React

### ISSUE THREAD

**Issue by Ella-e** [markmap/markmap#252]
In the provided react demo, if I uncomment lines regarding the toolbar, there will be an error display. And when I try to follow the doc to use markmap-toolbar in my own project, the toolbar component shows nothing. May I know if there is currently something wrong with the markmap-toolbar for React? Or does anyone know how to enable toolbar of markmap in a React project?

**Additional context**
Here is a screenshot of the error from the react demo:
<img width="1169" alt="image" src="https://github.com/markmap/markmap/assets/60089102/6ea6c0c5-0f5f-4e07-a589-7086f80e1617">

**Comment by gera2ld** [comment]
It's because Stackblitz cannot import the correct file. You can check this one instead: https://stackblitz.com/edit/markmap-react

**Comment by Ella-e** [comment]
It works now, thank you!
