### ISSUE TITLE
[BUG]  array.at function is too new, some old browser can't support it

### ISSUE THREAD

**Issue by amin2312** [markmap/markmap#255]
function getCurrentHeading(level: Levels) {
    let heading: IHtmlNode | undefined;
    while ((heading = headingStack.at(-1)) && heading.level >= level) {
      headingStack.pop();
    }
    return heading || rootNode;
  }

headingStack.at it will catch is some old browser, because it must be run above chrome 92,
please replace to: headingStack[headingStack.length - 1]

**Comment by quibbler01** [comment]
it can be chrome 92
