### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by flowerhaha** [markmap/markmap#256]
- [ ] I have searched for existing issues that already reported this problem and found none
- [x] The bug is present in [REPL](https://stackblitz.com/edit/markmap-react?file=src%2Fstyle.css)
 
**Describe the bug**
there is a typeError when i generate a new markmap, Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'refreshHook'). i try to find the reason, but This example also reports the same error [https://stackblitz.com/edit/markmap-react?file=src%2Fstyle.css]

how can i fix it , please help me, thank you

**Comment by wlk-menglan** [comment]
me too

**Comment by trry-hub** [comment]
me too

**Comment by wlk-menglan** [comment]
来信已收到！顺祝您身体健康！Thank for your email , Good Health and Happy!!

**Comment by gera2ld** [comment]
Thanks @Adonis0123

**Comment by flowerhaha** [comment]
Thank you very much @Adonis0123
