### ISSUE TITLE
[BUG] boolbase doesn't provide an export named: 'default'

### ISSUE THREAD

**Issue by zillionare** [markmap/markmap#259]
- [ x] I have searched for existing issues that already reported this problem and found none
- [x ] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**

I have used markmapjs in my slidev theme: slidev-theme-rich. It all worked well both at my local, and demo site(build then published).

However, the package I've published to npmjs, doesn't work, it says:

```
boolbase doesn't provide an export named: 'default'
```

**To Reproduce**

1. install slidev by `npm i @slidev/cli
2. write an example.md:

```
---
theme: rich
---

---

# the markmap

<Markmap class="abs top-400px left-50px w-full">

```
## level1
```
</Markmap>

```

3. run npx slidev example.md, you'll got the error.

**Expected behavior**

the expected screen should be looked like: 

![Live Demo](https://zillionare.github.io/slidev-theme-rich/4)

**Actual behavior**

The page could not rendered:

<img width="733" alt="图片" src="https://github.com/markmap/markmap/assets/7206696/09ad8e22-aefd-4191-9df9-a45eaeef1b2a">

**Environment:**

- OS: macOS, m1
- Browser: firefox
- Browser Version: not related

```
slidev-theme-rich@0.3.0 /Users/aaronyang/slidev-theme-rich
└─┬ markmap-lib@0.17.0
  └─┬ markmap-html-parser@0.17.0
    └─┬ cheerio@1.0.0-rc.12
      └─┬ cheerio-select@2.1.0
        ├── boolbase@1.0.0
        └─┬ css-select@5.1.0
          ├── boolbase@1.0.0 deduped
          └─┬ nth-check@2.1.1
            └── boolbase@1.0.0 deduped
```

**Additional context**

**Comment by gera2ld** [comment]
You may need to prebundle `markmap` for `slidev` to use. I don't know much about `slidev` so there is nothing much I can help.
