### ISSUE TITLE
Cannot open hyperlink out the html.

### ISSUE THREAD

**Issue by ShouyeLiu** [markmap/markmap#262]
I try to embed html generated by markmap into sphinx, and an error occur when I click hyperlink in the mindmap:

Firefox Can’t Open This Page

To protect your security, www.nature.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.

[Learn more…](https://support.mozilla.org/1/firefox/128.0/Darwin/en-US/xframe-neterror-page)

How to to do so that when Iclick the hyperlink, an external new web tab will be opened?

**Comment by gera2ld** [comment]
https://github.com/markmap/markmap/issues/129
