### ISSUE TITLE
Request for Source Code: Markmap REPL Demo

### ISSUE THREAD

**Issue by Achilles822** [markmap/markmap#263]
Hi there!

I hope this message finds you well. I've been exploring the fantastic Markmap library and I'm particularly impressed by the REPL demo available at https://markmap.js.org/repl.

I was wondering if it would be possible to get access to the source code for this demo? It would be incredibly helpful for my learning process and understanding how to implement similar functionality in my own projects.

I completely understand if the source code isn't publicly available, but I thought it wouldn't hurt to ask. Any insights or guidance you could provide would be greatly appreciated.

Thank you so much for your time and for creating such a useful tool!

Best regards

**Comment by gera2ld** [comment]
Thanks for reaching out. The website might be a bit overcomplicated as a demo, so I suggest you check out the demos at https://markmap.js.org/docs/markmap instead.

**Comment by Achilles822** [comment]
> Thanks for reaching out. The website might be a bit overcomplicated as a demo, so I suggest you check out the demos at https://markmap.js.org/docs/markmap instead.

Thank you so much for your quick response and guidance! I've checked out the demos you suggested, and they're indeed very helpful and straightforward.

I'm particularly interested in implementing a full-screen feature similar to what's available in the REPL demo. Would it be possible to provide a simple example or some pointers on how to achieve this full-screen functionality? I understand if it's not readily available, but any tips or direction would be greatly appreciated.

Thank you again for your time and for creating such a versatile tool!
