### ISSUE TITLE
[BUG] 项目不允许使用外部cdn，如何删除？

### ISSUE THREAD

**Issue by Oralinge** [markmap/markmap#264]
<img width="753" alt="image" src="https://github.com/user-attachments/assets/eebcaa18-3297-4683-acf1-251f88d1f48e">

**Comment by gera2ld** [comment]
```ts
import { Transformer } from 'markmap-lib/no-plugins';
```

Ref: https://markmap.js.org/docs/packages--markmap-lib#importing
