### ISSUE TITLE
how can I load the KaTeX fonts using local resources or change Transformer ？

### ISSUE THREAD

**Issue by zyhxwing** [markmap/markmap#266]
- [x] I have searched for existing issues that already reported this problem and found none
- [x] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**
Hey bro, your component library is awesome and perfectly meets my needs. However, due to my network restrictions, I can't use a CDN to load the KaTeX fonts. So I wanted to ask, how can I load the KaTeX fonts using local resources? I'm sorry, but I couldn't find any instructions about this in the documentation

**Additional context**
![image](https://github.com/user-attachments/assets/d5f8377b-7568-48a1-acdc-cedc26c362bf)

**Comment by gera2ld** [comment]
If you do not need Katex at all, you can just disable the plugin by removing it.

If you need to load Katex as well as other assets from a different URL, try using a custom URL provider:

https://github.com/markmap/markmap/blob/d52783b631c9e9cd3c29c1826f8c7b1aa23f62ff/packages/markmap-cli/src/index.ts#L72-L73
https://github.com/markmap/markmap/blob/d52783b631c9e9cd3c29c1826f8c7b1aa23f62ff/packages/markmap-cli/src/util.ts#L49-L51
