### ISSUE TITLE
[BUG] first impression error

### ISSUE THREAD

**Issue by OceanBelongsToMe** [markmap/markmap#267]
- [x] I have searched for existing issues that already reported this problem and found none
- [x] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**
Dynamically create svg and then bind markmap, displayed for the first time, as shown in the figure:
<img width="1205" alt="image" src="https://github.com/user-attachments/assets/449a5efa-3ef2-4042-8fc5-7ad6edbebf26">

**To Reproduce**

**Expected behavior**
This is my core code：
```ts
import { Transformer } from "markmap-lib";
import { Markmap, loadCSS, loadJS } from 'markmap-view';


// With default plugins
const transformer = new Transformer();
export function createMindHover(markdown: string) {
    const { root, features } = transformer.transform(markdown);

    const assets = transformer.getUsedAssets(features);
    let { styles, scripts } = assets;

    if (styles) loadCSS(styles);
    if (scripts) loadJS(scripts, { getMarkmap: () => Markmap });

    const svgElement = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    let mm = Markmap.create(svgElement);
    mm.setData(root);
    return { mm, svgElement };
}
```

```ts
let wordHover = hoverTooltip((view, pos, side) => {
        let { from, to, text } = view.state.doc.lineAt(pos);
        let start = pos,
            end = pos;
        while (start > from && /\w/.test(text[start - from - 1])) start--;
        while (end < to && /\w/.test(text[end - from])) end++;
        if ((start == pos && side < 0) || (end == pos && side > 0)) return null;
        return {
            pos: start,
            end,
            above: true,
            create(view) {
                let dom = document.createElement("div");
                let m: Markmap;
                return {
                    dom,
                    mount(view) {
                        let { svgElement, mm } = createMindHover(value);
                        m = mm;
                        dom.appendChild(svgElement);
                        _resizeMarkmap(m, 1.1);
                    },
                    positioned(space) {
                        // _resizeMarkmap(m, 1.1);
                    },
                    resize: false,
                };
            },
        };
    });
```

**Actual behavior**

**Environment:**

- OS: [e.g. macOS]
- Browser: [e.g. chrome, safari]
- Browser Version: [e.g. 22]

**Additional context**

**Comment by gera2ld** [comment]
I don't really understand what the desired behavior is from your description. It's better to provide a reproduction project.

Anyway `markmap` can only calculate sizes and positions after styles are applied, i.e. CSS are loaded properly and the container is attached to the DOM. So I guess you need to set data or call `mm.fit()` after it is attached to the DOM.

Here is an example: https://stackblitz.com/edit/markmap-dynamic?file=src%2Fmarkmap-hooks.tsx
