### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yaolifeng0629** [markmap/markmap#272]
- [x] I have searched for existing issues that already reported this problem and found none
- [x] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**
Statistical unordered lists and code blocks cannot be displayed

**To Reproduce**
```markdown
### Blocks
- test
```
```js
console.log('hello, JavaScript')
```

```js
console.log('hello, JavaScript')
```

**Expected behavior**

**Actual behavior**

**Environment:**

- OS: Windows
- Browser: Chrome
- Browser Version: 128.0.6613.84

**Additional context**

![Clip_2024-08-23_11-25-12](https://github.com/user-attachments/assets/6331bf7d-b85b-4369-9ed8-9c88817ca87e)

**Comment by Arkshine** [comment]
Having a list and a block at the same level is not supported currently.

**Comment by yaolifeng0629** [comment]
> Having a list and a block at the same level is not supported currently.

That's ok, thanks
