### ISSUE TITLE
[BUG] window.markmap is undefined

### ISSUE THREAD

**Issue by sigma-plus** [markmap/markmap#282]
- [x] I have searched for existing issues that already reported this problem and found none
- [] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**

loadJS()  has `getMarkmap().refreshHook.call()`, but the getMarkmap() is undefined . You can see this bug   In Vue demo  https://stackblitz.com/edit/markmap-vue?file=src%2Fapp.vue

**To Reproduce**

https://stackblitz.com/edit/markmap-vue?file=src%2Fapp.vue

**Expected behavior**

**Actual behavior**

**Environment:**

- OS: [e.g. macOS]
- Browser: [e.g. chrome, safari]
- Browser Version: [e.g. 22]

**Additional context**

**Comment by gera2ld** [comment]
Updated.
