### ISSUE TITLE
How to add linebreak label

### ISSUE THREAD

**Issue by baimuchu** [markmap/markmap#288]
Thanks the author for the auto-linebreak with `maxWidth`, but I still want to new line by diffierent condition. I try to use `<br>`. But it doesn't work.

**Comment by gera2ld** [comment]
Not sure what you are talking about. Please fill the issue template and provide a minimal reproduction.

**Comment by baimuchu** [comment]
Sorry for the unclear description.
I use API: `markmap-autoloader`, I want to do a linebreak in a long text line. But when I use `<br>` or `<br />`, it doesn't work.
The reproduction code :
```
<style>
    .markmap {
        position: relative;
    }
    .markmap > svg {
        width: 100%;
        height: 300px;
    }
</style>

<div class="markmap">
    <script src="https://cdn.jsdelivr.net/npm/markmap-autoloader@latest"></script>
    ---
    title: xxxxxx
    ---
    # xxxxxxx <br> yyyy.
    ## zzzzz
</div>
```
<img width="678" alt="Screenshot 2024-11-21 at 20 54 30" src="https://github.com/user-attachments/assets/1367e5d9-0df1-4f99-acc1-ea0566ab9989">
