### ISSUE TITLE
Support for node click events

### ISSUE THREAD

**Issue by devgid** [markmap/markmap#290]
I would like it to have functionality where one can click on a node and then go back to the original markdown header.

If it can support events then click back event can be written by extension developers

**Comment by gera2ld** [comment]
`mm.svg` is a `D3.Selection` so you can do this:

```ts
mm.svg.selectAll('foreignObject').on('click', (e: PointerEvent, d: FlextreeNode<INode>) => {
  console.log('Event:', e);
  console.log('Data:', d);
});
```

**Comment by Seven430** [comment]
Could you please advise on how I can use this to click on one node and navigate to another node?
