### ISSUE TITLE
[SMALL BUG] MarkMap logo is not shown after download the repl as `.svg`

### ISSUE THREAD

**Issue by migueleliasweb** [markmap/markmap#295]
- [x] I have searched for existing issues that already reported this problem and found none
- [x] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**

The MarkMap logo is not shown if the `repl` is downloaded as an `.svg`.

This is due to the favicon being set as a relative URL. When the `.svg` is created, the base hostname is not added to the file location, making it not to be shown correctly.

**To Reproduce**

Click on `Download as SVG` on the repl https://markmap.js.org/repl

**Expected behavior**

The MarkMap logo should be shown in the exported `.svg`.

**Actual behavior**

Image not shown.

**Comment by gera2ld** [comment]
Updated the demo. Thanks.
