### ISSUE TITLE
[BUG] I'm not able to create a 7 child, if I add more than 6 #, the 7th one is not detected

### ISSUE THREAD

**Issue by javimofe** [markmap/markmap#297]
- [x] I have searched for existing issues that already reported this problem and found none
- [x] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Environment:**

- OS: [e.g. macOS]
- Browser: [e.g. chrome, safari]
- Browser Version: [e.g. 22]

**Additional context**

**Comment by gera2ld** [comment]
https://markmap.js.org/docs/faq#why-cant-i-have-more-than-6-levels-of-
