### ISSUE TITLE
[Feature Request] Can `markmap-cli` compile a whole folder of md files at once?

### ISSUE THREAD

**Issue by jaywhj** [markmap/markmap#298]
Hello，can `markmap-cli` compile a whole folder of md files at once?  

Like this, for example:  `markmap docs/` , all md files under the folder `docs` are compiled.

**Comment by gera2ld** [comment]
You can easily achieve this with `xargs`:

```bash
find docs/ -name "*.md" -print0 | xargs -0 -I {} markmap {}
```
