### ISSUE TITLE
Add parse options to include / exclude nodes by types

### ISSUE THREAD

**Issue by gera2ld** [markmap/markmap#71]
There are nodes or parts that we may or may not want to render:

- code blocks
- images
- ...

We need an option for the parser (markmap-lib) to know whether a node should be included in the result.

**Comment by dvargas92495** [comment]
What's a good way to handle Images? It seems like the size is not taken into account because the image still needs to load. Is there a way to either set size parameters before `create` or resize the node after `create`?

**Comment by gera2ld** [comment]
> What's a good way to handle Images? It seems like the size is not taken into account because the image still needs to load. Is there a way to either set size parameters before `create` or resize the node after `create`?

Try `markmap.refreshHook.call()` after the image is loaded. You can also set width and height for the image element or its wrapper.

I'll hide these comments since they are off topic. Please ask questions in Discussions or new issues.

**Comment by PeterWang-dev** [comment]
so any updates?

**Comment by hwy1782** [comment]
so any updates?

**Comment by dhtoran** [comment]
Any update? also, the workaround of commenting out the frontmatter with  does not work well

**Comment by stellarkey** [comment]
I used some **Regular Expression** tricks to achieve the same result.

Here are some examples:

```javascript
dst = document.getElementById("MarkMap");

// remove code block
dst.innerHTML = dst.innerHTML.replace(/```(.|\n)+?```/g, "QAQ");
//remove quote block
dst.innerHTML = dst.innerHTML.replace(/(\n\>(\s\>)*)|(\n&gt;(\s&gt;)*)/g, "\nQAQ");
//remove table block
dst.innerHTML = dst.innerHTML.replace(/\n(\|\s\-+\s)+\|/g, "\nQAQ");

markmap.autoLoader.renderAll();
```

The above lines just replace every block with "QAQ", preventing markmap from rendering them.

And it works fine for me.

@dhtoran @hwy1782

**Comment by OMPower** [comment]
I use obsidian to take notes, and the plug-in mindmap is based on this repository. Code blocks will distort the mind map.

**Comment by souovan** [comment]
Hi y'all a time ago i saw a issue asking for a sticky note implementation to markmap, but i can't find it now. What do you guys think of quotes being rendered as sticky notes to the node they are attached to ?

**Comment by silopolis** [comment]
This is a must-have, AFAIC, because without it, Markmap is sadly barely usable for long, deeply structured documents.

Extra ball: Add option to make nodes "foldable" into parent node (see #89 too).

**Comment by gera2ld** [comment]
https://markmap.js.org/docs/json-options#htmlparser

Try it in [REPL](https://markmap.js.org/repl).
