### ISSUE TITLE
use heading together with Unordered List

### ISSUE THREAD

**Issue by lambone** [markmap/markmap#80]
VS code Version: 1.56.2
Markmap: 0.0.9

when I try to add some unordered list start with "-", the preview seems mixed with next level of heading "#", is that the expected behaviour?  

But in my case, in general, I usually add some context paragraph. but use "#" headings to organise the structure.

**Comment by gera2ld** [comment]
It is the expected behavior by now but obviously not correct. Maybe the unordered list should be rendered as appendix instead of subtree.

**Comment by Giessen** [comment]
is this a (temp) workaround to show deeper than 6 levels heading?

**Comment by gera2ld** [comment]
@Giessen your question doesn't seem to be related to this issue. Maybe you want to check [faq](https://markmap.js.org/docs/faq).
