### ISSUE TITLE
Feature request: support image markdown syntax

### ISSUE THREAD

**Issue by shikbupt** [markmap/markmap#88]
inserting image into the mindmap is a great feature

**Comment by invincible1900** [comment]
Really great feature!

**Comment by qq897425998** [comment]
Really great feature!

**Comment by XiaoPanPanKevinPan** [comment]
It seems to be supported, but the images become so~ small.

![image](https://user-images.githubusercontent.com/44266832/179148506-c07e5e6d-93df-40db-a023-8f8d4fbb5b2c.png)
