### ISSUE TITLE
How to add click/hover events?

### ISSUE THREAD

**Issue by xwiz** [markmap/markmap#93]
Hi great work with the library. Can you provide a readme/guide for adding like click/hover events

**Comment by yurenji** [comment]
+1 need this feature

**Comment by yifeishu-com** [comment]
+1 need this feature

**Comment by yifeishu-com** [comment]
1. Can you add `data-position` attribute in `foreignObject DOM` in `markmap-view` package?
emm... I can add `click` event on the outer`SVG DOM`.

2. Can you support `JSON tree transform function` in `markmap-lib`?

**Comment by legend80s** [comment]
+1 need this feature

**Comment by zillionare** [comment]
+1 need this feature

**Comment by gera2ld** [comment]
You can get the SVG element as a d3 selection from the Markmap instance, so:

```js
// Get the SVG
const $svg = mm.svg;

// Handle events in d3 way
$svg.on('click', () => { alert('clicked'); });
```

References:

- Markmap::svg - https://markmap.js.org/api/classes/markmap_view.Markmap.html#svg
- D3-selection - Handling events - https://d3js.org/d3-selection/events
